config/routes.rb
Rails.application.routes.draw do
	
	resources :recipes do
		collection do
            get :search
        end
	end

	resources :recipes
	
	root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe, inverse_of: :directions
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe, inverse_of: :ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_many :ingredients, inverse_of: :recipe
	has_many :directions, inverse_of: :recipe

	accepts_nested_attributes_for :ingredients,
									reject_if: proc { |attributes| attributes['name'].blank? },
									allow_destroy: true
	accepts_nested_attributes_for :directions,
									reject_if: proc { |attributes| attributes['step'].blank? },
									allow_destroy: true

	validates :tittle, :description, :image, presence: true
	has_attached_file :image, styles: { :medium => "400x400#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]

	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show

	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)

		if @recipe.save
			redirect_to @recipe, notice: "Przepis zostal dodany"
		else
			render 'new'
		end
	end

	def edit
	end
	def search
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Przepis zostal usuniety"
	end


	private

	def recipe_params
		params.require(:recipe).permit(:tittle, :description, :portion, :preparation_time, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy]  )
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title Amanda project
		= stylesheet_link_tag    'application', media: 'all'
		= javascript_include_tag 'application'
		= csrf_meta_tags

	%body
		%nav.navbar.navbar-default
			.container
				.navbar-brand= link_to "Amanda project", root_path
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Dodaj nowy przepis", new_recipe_path
					%li= link_to "Szukaj przepisu", search_recipes_path
		.container
			- flash.each do |name, msg|
				= content_tag :div, msg, class: "alert"
		= yield

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: "form-input form-control" }
		= link_to_remove_association "Usun", f, class: "form-button btn btn-default"

app/views/recipes/_form.html.erb
=simple_form_for @recipe, html: {multipart: true} do |f|
- if recipe/errors/any?
#errors
%p
= @recipe.errors.count
Prevent this recipe from saving
%ul
- @recipe.errors.full_messages.each do |msg|
%li = msg
.panel-body
= f.input :title, input_html: { class: 'form-control' }
= f.input :description, input_html: { class: 'form-control' }

= f.button :submit, class: "btn btn-primary"

app/views/recipes/_form.html.haml
=simple_form_for @recipe, html: {multipart: true} do |f|
	- if @recipe.errors.any?
		#errors
			%p
			= @recipe.errors.count
			Prevent this recipe from saving
		%ul
			- @recipe.errors.full_messages.each do |msg|
				%li= msg
	.panel-body
		= f.input :tittle, input_html: { class: 'form-control' }
		= f.input :description, input_html: { class: 'form-control' }
		= f.input :image, input_html: { class: 'form-control' }
		.row
			.col-md-2
				= f.input :preparation_time, :label => "Czas przygotowania", input_html: { class: 'form-control' }
			.col-md-2
				= f.input :portion, :label => "Ilość porcji", input_html: { class: 'form-control' }
		.row
			.col-md-6
				%h3 Skladniki
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Dodaj skladnik', f, :ingredients, class: "btn btn-default add-button"
			.col-md-6
				%h3 Wskazowki
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Dodaj krok', f, :directions, class: "btn btn-default add-button"


		= f.button :submit, class: "btn btn-primary"

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: "form-input form-control" }
		= link_to_remove_association "Usun", f, class: "form-button btn btn-default"

app/views/recipes/edit.html.haml
%h1 Edytuj przepis

= render 'form'

app/views/recipes/index.html.erb
test

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
	.row
		- recipes.each do |recipe|
			.col-md-4
				.recipe
					.image_wrapper
						= link_to recipe do 
							= image_tag recipe.image.url(:medium)
					%h2= link_to recipe.tittle, recipe

app/views/recipes/new.html.haml
%h1 Nowy przepis

=render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/search.html.haml
%p is search

app/views/recipes/show.html.haml
.main_content
	#recipe_top.row
		.col-md-4
			= image_tag @recipe.image.url(:medium), class: "recipe_image"
		.col-md-8
			#recipe_info
				%h1= @recipe.tittle
				%p= @recipe.description
	.row
		.col-md-2
			#Parameters
				%p Czas przygotowania: #{number_with_precision(@recipe.preparation_time, precision: 0)} min.
				%p Ilość porcji: #{@recipe.portion}
	.row
		.col-md-6
			#ingredient
				%h2 Skladniki:
				%ul
					- @recipe.ingredients.each do |ingredient|
						%li= ingredient.name

		.col-md-6
			#directions
				%h2 Wskazówki
				%ul
					- @recipe.directions.each do |direction|
						%li= direction.step

	.row
		.col-md-12
			= link_to "Back", root_path, class: "btn btn-default"
			= link_to "Edytuj", edit_recipe_path, class: "btn btn-default"
			= link_to "Usun", recipe_path, method: :delete, data: {confirm: "czy napewno?" }, class: "btn btn-default"